### ISSUE TITLE
Incompatibility with Bundler 1.14.6

### ISSUE THREAD

**Issue by Tonkpils** [byroot/bootscale#44]
There seems to be an incompatibility with bundler 1.14.6 when starting a Rails app with bootscale installed. See https://github.com/bundler/bundler/issues/5547 for more details. I'll be digging into this on my end but I figured someone here could shine on some knowledge on this?

**Comment by grosser** [comment]
error is:

```
/Users/leo/.rvm/gems/ruby-2.3.1@Candi/gems/bundler-1.14.6/lib/bundler/runtime.rb:94:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'faker'. (Bundler::GemRequireError)
Gem Load Error is: wrong number of arguments (given 0, expected 1)
```

from:
```
/Users/leo/.rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/path_support.rb:25:in `initialize'
```

so most likely because we are overriding require or some other internal Bundler.require is using ...
line 94 is just the re-raise though https://github.com/bundler/bundler/blob/master/lib/bundler/runtime.rb#L94 

need to dig deeper to find out where exactly it is raising the original error ... can you rescue the error and print `exception.cause` ?

**Comment by Tonkpils** [comment]
Ok, so I ended up removing the `tmp/bootscale` directory and I can't reproduce the issue anymore. If I run into this again I'll re-open. Apologies!
